version: '3'

services:
 zap:
  image: cyberkru/zapci
  ports:
   - 8090:8090
  logging:
   driver: "none"
 scan:
  build:
   context: ./scan
  environment:
   - PROXY_URL=http://zap:8090
   - TARGET_URL=${TARGET_URL}
   - DOJOKEY=${DOJOKEY}
   - DOJOIP=${DOJOIP}
   - EGID=${EGID}
  volumes:
   - "$PWD/output:/app/output"
  depends_on:
   - zap
